### PR TITLE
Update CountryRepository.java

### PR DESCRIPTION
**Pull request by ifalko**

### CODE REVIEW

**Comment by dsyer** [comment]
Doesn't seem like a very interesting change (no change in functionality). Can you explain what it does and why?

**Comment by gregturn** [comment]
@dsyer It appears to simplify the lookup (`List` to `Map`) in exchange for a slightly more complicated build up (name of the country as key is used in two places).

As you said, no REAL change in functionality, so not sure this is needed.

**Comment by ifalko** [comment]
Guys, are you serious?
Functionality does not change, but using List is not correct from the point of view of the logic of work. Linearly search for a necessary country in the list with a check in the block if...
The data structure was not selected correctly.
Using an deprecated method is also not good practice. 
So let's not use deprecated methods and incorrectly selected data structures in the example, please.

**This is a tutorial for beginners!** Do not forget about it

**Comment by gregturn** [comment]
Can you squash and debase against the master branch?

**Comment by ifalko** [comment]
ok, continue to use array for lookup by name

**Comment by dsyer** [comment]
Thank you for the contribution, and for sharing your opinions, but please try to moderate your tone, and remain calm. If you want us to merge a PR you only have to explain what it is for (you submitted this one with an empty log and no comment). Greg asked you to rebase? Are you saying you don't want to make this change now?

**Comment by ifalko** [comment]
I'am sorry, but i did not start to write with CAPS, as Greg:  "no REAL
change in functionality, so not sure this is needed."
Therefore "please try to moderate your tone, and remain calm"

2017-04-18 13:29 GMT+03:00 Dave Syer <notifications@github.com>:

**Pull request merged**
