### PR TITLE
Change tabs to 4 spaces

### PR DESCRIPTION
**Pull request by mamadaliev**
Hey @spring-guides! 
I changed all tabs to 4 spaces in all places. Before that, there were different tabs in different places.
Please merge this MR if you think it is correct. Thank you.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mamadaliev Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-producing-web-service&pullRequestId=36)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-producing-web-service&pullRequestId=36) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mamadaliev Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-producing-web-service&pullRequestId=36)!

**Comment by mamadaliev** [comment]
Discrepancy can be seen due to the different tabs on the guide page.

image

**Comment by Buzzardo** [comment]
The Spring team uses tabs. If there are too many tabs somewhere, the fix is to adjust the number of tabs rather than switch to spaces. Thanks.

**Pull request closed without merging**
